fix: further simplification

diff --git a/.helpers/prereq_functions b/.helpers/prereq_functions
--- a/.helpers/prereq_functions
+++ b/.helpers/prereq_functions
@@ -18,7 +18,7 @@ download() {
 
 download_run_script() {
   local url=$1 script=`download "$url"`
-  sh -c "$script"
+  bash -c "$script"
 }
 
 use_homebrew() {
@@ -27,7 +27,7 @@ use_homebrew() {
   elif [ "$uname" = "Darwin" ]; then
     eval "$(/usr/local/bin/brew shellenv)"
   else
-    >&2 echo "Unsupported OS type.  Cannot continue."
+    >&2 echo "Unsupported OS type. Cannot continue."
     exit 1
   fi
 }
@@ -36,7 +36,7 @@ get_sudo() {
   if [ \( `whoami` != "root" \) -a \( -z "$SUDOER" \) ]; then
     if installed sudo; then
       export SUDO=`command -v sudo`
-      echo 'Attempting to get sudo access.  Your password may be required.'
+      echo 'Attempting to get sudo access. Your password may be required.'
       echo 'Some features may not be available if you are not a sudoer.'
       if $SUDO -v; then
         export SUDOER=1
